# *PANDAS*

In [2]:
import pandas as pd
import numpy as np

In [3]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# ***DATAFRAME CREATION***

In [4]:
df = pd.DataFrame(data=np.arange(0,20).reshape(5,4), index=["Row1","Row2","Row3","Row4","Row5"] , columns=["Column1","Column2","Column3","Column4"])

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df.head()

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

# **INDEXING**

In [7]:
## 1. DIRECT BY USING COLUMN NAME
df[["Column1" , "Column2"]]

      Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17

In [8]:
## 2. BY USING ROWINDEX[LOC]
df.loc[['Row2', 'Row3']]

      Column1  Column2  Column3  Column4
Row2        4        5        6        7
Row3        8        9       10       11

In [9]:
## 3. ROWINDEX COLUMNINDEX[.ILOC]

In [10]:
df.iloc[2:4, 0:2]

      Column1  Column2
Row3        8        9
Row4       12       13

# **CONVERT DARAFRAME INTO ARRAYS**

In [11]:
df.iloc[2:4, 0:2].values

array([[ 8,  9],
       [12, 13]])

### *BASIC OPERATIONS *

In [12]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

# *PART -------- 2*

In [1]:
## reading different data sources with the help of pandas
## pandas read csv file , stringIO
from io import stringIO
import pandas as pd
## df = pd.read_csv('file_name')
StringIO(data) ## in memoory file format object
## to read file
pd.read_csv(stringIO(data))

ImportError: cannot import name 'stringIO' from 'io' (/usr/lib/python3.12/io.py)